name: Preview

on: pull_request

jobs:
  publish-previews:
    name: Publish Previews
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: thefrontside/actions/publish-pr-preview@v1.7
        name: Publish PR Preview
        with:
          BEFORE_ALL: echo "registry=https://npm.pkg.github.com" >> ~/.npmrc && echo "//npm.pkg.github.com/:_authToken=${ secrets.GITHUB_TOKEN }" >> ~/.npmrc
          IGNORE: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}