name: Preview

on: pull_request

jobs:
  publish-previews:
    name: Publish Previews
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: thefrontside/actions/publish-pr-preview@v1.7
        name: Publish PR Preview
        with:
          BEFORE_ALL: yarn build:ci
          IGNORE: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}