name: Publish Github Pages

on:
  push:
    branches:
      - master

jobs:
  delpoy:
    # Job name is Greeting
    name: Deploy Site
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Deps and Build
        run: |
          yarn
          yarn build
      - name: Build docs
        run: yarn docs
      - name: Publish site and docs
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: ./
          keep_history: true
          fqdn: shepherdjs.dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}