name: Run Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.13.0-chrome78-ff70
    name: Test Shepherd.js
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Run the test
        run: yarn test:unit:ci
      - name: Coverage
        run: |
          yarn rewrite-paths
          codeclimate-test-reporter < coverage/lcov.info