name: Run Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Test Shepherd.js
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Unit Tests
        run: yarn test:unit:ci

